// Counter Type
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const MULTIPLY = "MULTIPLY";

// Fake Store Type
export const FAKE_STORE_DATA_LOADING = "FAKE_STORE_DATA_LOADING";
export const FAKE_STORE_DATA_SUCCESS = "FAKE_STORE_DATA_SUCCESS";
export const FAKE_STORE_DATA_ERROR = "FAKE_STORE_DATA_ERROR";
export const FAKE_STORE_ACTION_MAIN = "FAKE_STORE_ACTION_MAIN";

// News Type
export const NEWS_DATA_REQUEST = "NEWS_REQUEST";
export const NEWS_DATA_LOADING = "NEWS_LOADING";
export const NEWS_DATA_SUCCESS = "NEWS_SUCCESS";
export const NEWS_DATA_ERROR = "NEWS_ERROR";
